/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package all_about_gui;

import Objects.MyConnection;
import Objects.Admin;
import Objects.Book;
import Objects.Member;
import Objects.User;
import java.awt.Color;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author red_k
 */
public class AdminPanel extends javax.swing.JFrame {

    String userName = "";
    
    public AdminPanel() {
        initComponents();
        jPanel4.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
        this.setBackground(new Color/*.HSBtoRGB*/(0,0,0,0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        bookPanel = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        bookOpPanel = new javax.swing.JPanel();
        bookSortButton = new javax.swing.JButton();
        bookSortCBox = new javax.swing.JComboBox<>();
        bookName = new javax.swing.JTextField();
        bookFindButton = new javax.swing.JButton();
        bookID = new javax.swing.JTextField();
        bookDelButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bookAddButton = new javax.swing.JButton();
        bookName1 = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        publisher = new javax.swing.JTextField();
        category = new javax.swing.JTextField();
        imgURL = new javax.swing.JTextField();
        pageURL = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        userOpPanel = new javax.swing.JPanel();
        userSortButton = new javax.swing.JButton();
        opUsername = new javax.swing.JTextField();
        deleteUserButton = new javax.swing.JButton();
        findUserButton = new javax.swing.JButton();
        userType = new javax.swing.JComboBox<>();
        giveAdminBut = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(204, 204, 204));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel4.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 4, 20, 20));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jTabbedPane1.setBackground(new java.awt.Color(0, 51, 51));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setOpaque(true);

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Author", "Publisher", "Category", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bookPanel.setViewportView(bookTable);

        bookOpPanel.setBackground(new java.awt.Color(102, 102, 102));
        bookOpPanel.setOpaque(false);

        bookSortButton.setBackground(new java.awt.Color(153, 153, 153));
        bookSortButton.setText("Show");
        bookSortButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bookSortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookSortButtonActionPerformed(evt);
            }
        });

        bookSortCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Here", "All", "Bilim Kurgu", "Fantastik", "Korku Gerilim", "Macera" }));
        bookSortCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookSortCBoxActionPerformed(evt);
            }
        });

        bookName.setText("(title, author, publisher)");
        bookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNameActionPerformed(evt);
            }
        });

        bookFindButton.setBackground(new java.awt.Color(153, 153, 153));
        bookFindButton.setText("Find");
        bookFindButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bookFindButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFindButtonActionPerformed(evt);
            }
        });

        bookID.setText("Enter ID here");
        bookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIDActionPerformed(evt);
            }
        });

        bookDelButton.setBackground(new java.awt.Color(153, 153, 153));
        bookDelButton.setText("Delete");
        bookDelButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bookDelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookDelButtonActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel7.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Title:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Author:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Publisher:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Category:");

        bookAddButton.setBackground(new java.awt.Color(153, 153, 153));
        bookAddButton.setText("ADD");
        bookAddButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bookAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAddButtonActionPerformed(evt);
            }
        });

        imgURL.setText("Image URL");

        pageURL.setText("Page URL");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(bookAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(author)
                                    .addComponent(bookName1)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(publisher)
                                    .addComponent(category)))
                            .addComponent(imgURL)
                            .addComponent(pageURL))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bookName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imgURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pageURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookAddButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout bookOpPanelLayout = new javax.swing.GroupLayout(bookOpPanel);
        bookOpPanel.setLayout(bookOpPanelLayout);
        bookOpPanelLayout.setHorizontalGroup(
            bookOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookOpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bookSortCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookName)
                    .addGroup(bookOpPanelLayout.createSequentialGroup()
                        .addGroup(bookOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bookOpPanelLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(bookDelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bookOpPanelLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(bookSortButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bookOpPanelLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(bookFindButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        bookOpPanelLayout.setVerticalGroup(
            bookOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookOpPanelLayout.createSequentialGroup()
                .addComponent(bookSortCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookSortButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookFindButton)
                .addGap(13, 13, 13)
                .addComponent(bookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookDelButton)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookOpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bookOpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25))
                    .addComponent(bookPanel))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Book Operations", jPanel3);

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));

        userOpPanel.setBackground(new java.awt.Color(153, 153, 153));
        userOpPanel.setOpaque(false);

        userSortButton.setBackground(new java.awt.Color(153, 153, 153));
        userSortButton.setText("Show Users");
        userSortButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        userSortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSortButtonActionPerformed(evt);
            }
        });

        opUsername.setText("Username");
        opUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opUsernameActionPerformed(evt);
            }
        });

        deleteUserButton.setBackground(new java.awt.Color(153, 153, 153));
        deleteUserButton.setText("Delete");
        deleteUserButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        deleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserButtonActionPerformed(evt);
            }
        });

        findUserButton.setBackground(new java.awt.Color(153, 153, 153));
        findUserButton.setText("Find");
        findUserButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        findUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findUserButtonActionPerformed(evt);
            }
        });

        userType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usertype", "Admin", "Member" }));

        giveAdminBut.setBackground(new java.awt.Color(153, 153, 153));
        giveAdminBut.setText("Make Admin");
        giveAdminBut.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        giveAdminBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveAdminButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userOpPanelLayout = new javax.swing.GroupLayout(userOpPanel);
        userOpPanel.setLayout(userOpPanelLayout);
        userOpPanelLayout.setHorizontalGroup(
            userOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userOpPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(userOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userType, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(giveAdminBut, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userSortButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        userOpPanelLayout.setVerticalGroup(
            userOpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userOpPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(userType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userSortButton)
                .addGap(46, 46, 46)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(opUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(findUserButton)
                .addGap(11, 11, 11)
                .addComponent(deleteUserButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(giveAdminBut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kullanıcı Adı", "Ad", "Soyad", "Şifre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(userTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userOpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(userOpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("User Operations", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 234, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 860, 530));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all_about_gui/adminson.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void giveAdminButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giveAdminButActionPerformed
        try {
            Member member = new Member("", "", "", "");
            ArrayList<Member> temp = member.getUserList(opUsername.getText(), 2);
            User.registerUser("Admin", temp.get(0).getuName(), temp.get(0).getfName(), temp.get(0).getlName(), temp.get(0).getPassword());
        }catch (IndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(null, "Please check the username.");
        }
        catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_giveAdminButActionPerformed

    private void findUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findUserButtonActionPerformed
        try {
            String selectedValue = userType.getSelectedItem().toString();
            Member temp1 = new Member("", "", "", "");
            Admin temp2 = new Admin("", "");

            if(selectedValue.equals("Usertype"))
                JOptionPane.showMessageDialog(null, "Please select a usertype.");
            else if (selectedValue.equals("Member")){
                ArrayList<Member> list = temp1.getUserList(opUsername.getText(), 2);
                DefaultTableModel model = (DefaultTableModel) userTable.getModel();
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                Object[] row = new Object[4];

                for(int i = 0; i < list.size(); i++){
                    row[0] = list.get(i).getuName();
                    row[1] = list.get(i).getfName();
                    row[2] = list.get(i).getlName();
                    row[3] = list.get(i).getPassword();

                    model.addRow(row);
                }
            }
            else if(selectedValue.equals("Admin")){
                ArrayList<Admin> list = temp2.getUserList(opUsername.getText(), 2);
                DefaultTableModel model = (DefaultTableModel) userTable.getModel();
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                Object[] row = new Object[4];

                for(int i = 0; i < list.size(); i++){
                    row[0] = list.get(i).getuName();
                    //row[1] = list.get(i).getfName();
                    //row[2] = list.get(i).getlName();
                    row[3] = list.get(i).getPassword();

                    model.addRow(row);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_findUserButtonActionPerformed

    private void deleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserButtonActionPerformed
        String selectedValue = userType.getSelectedItem().toString();

        if(selectedValue.equals("Usertype"))
            JOptionPane.showMessageDialog(null, "Please select a usertype.");
        else
            User.delUser(opUsername.getText(), selectedValue);
    }//GEN-LAST:event_deleteUserButtonActionPerformed

    private void opUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opUsernameActionPerformed

    private void userSortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSortButtonActionPerformed
        try {
            String selectedValue = userType.getSelectedItem().toString();
            Member temp1 = new Member("", "", "", "");

            Admin temp2 = new Admin("", "");

            if(selectedValue.equals("Usertype"))
                JOptionPane.showMessageDialog(null, "Please select a usertype.");
            else if(selectedValue.equals("Member")){
                String str = "";
                ArrayList<Member>member = temp1.getUserList(selectedValue, 1);
                DefaultTableModel model = (DefaultTableModel) userTable.getModel();
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                Object[] row = new Object[4];

                for(int i = 0; i < member.size(); i++){
                    row[0] = member.get(i).getuName();
                    row[1] = member.get(i).getfName();
                    row[2] = member.get(i).getlName();
                    row[3] = member.get(i).getPassword();

                    model.addRow(row);
                }
            }
            else if(selectedValue.equals("Admin")){
                String str = "";
                ArrayList<Admin>list = temp2.getUserList(selectedValue, 1);
                DefaultTableModel model = (DefaultTableModel) userTable.getModel();
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                Object[] row = new Object[4];

                for(int i = 0; i < list.size(); i++){
                    row[0] = list.get(i).getuName();
                    row[3] = list.get(i).getPassword();

                    model.addRow(row);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_userSortButtonActionPerformed

    private void bookAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAddButtonActionPerformed
        Book.addBook(bookName1.getText(), author.getText(), publisher.getText(), category.getText());
        
        PreparedStatement ps;
        String query = "UPDATE `books` SET `img_url` = '" + imgURL.getText() + "', `info_url` = '" + pageURL.getText() + "' WHERE (`title` = '" + bookName1.getText() + "')";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        MyConnection.getPic(bookName1.getText());
    }//GEN-LAST:event_bookAddButtonActionPerformed

    private void bookDelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookDelButtonActionPerformed
        try{
            Book.delBook(Integer.parseInt(bookID.getText()));
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Please enter a valid ID.");
        }
    }//GEN-LAST:event_bookDelButtonActionPerformed

    private void bookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIDActionPerformed

    private void bookFindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFindButtonActionPerformed
        ArrayList<Book> list = Book.bookList(bookName.getText(), 2);
        DefaultTableModel model = (DefaultTableModel) bookTable.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        Object[] row = new Object[6];

        for(int i = 0; i < list.size(); i++){
            row[0] = list.get(i).getID();
            row[1] = list.get(i).getTitle();
            row[2] = list.get(i).getAuthor();
            row[3] = list.get(i).getPublisher();
            row[4] = list.get(i).getCategory();
            row[5] = list.get(i).getScore();

            model.addRow(row);
        }
        if(list.isEmpty())
            JOptionPane.showMessageDialog(null, "There is no such book in the system.");
    }//GEN-LAST:event_bookFindButtonActionPerformed

    private void bookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookNameActionPerformed

    private void bookSortCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookSortCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookSortCBoxActionPerformed

    private void bookSortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookSortButtonActionPerformed
        String selectedValue = bookSortCBox.getSelectedItem().toString();

        if(selectedValue.equals("Select Here"))
            JOptionPane.showMessageDialog(null, "Please select a category.");
        else{
            ArrayList<Book> list = Book.bookList(selectedValue, 1);
            DefaultTableModel model = (DefaultTableModel) bookTable.getModel();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            Object[] row = new Object[6];

            for(int i = 0; i < list.size(); i++){
                row[0] = list.get(i).getID();
                row[1] = list.get(i).getTitle();
                row[2] = list.get(i).getAuthor();
                row[3] = list.get(i).getPublisher();
                row[4] = list.get(i).getCategory();
                row[5] = list.get(i).getScore();

                model.addRow(row);
            }
        }
    }//GEN-LAST:event_bookSortButtonActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        LoginPanel lf = new LoginPanel();
        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField author;
    private javax.swing.JButton bookAddButton;
    private javax.swing.JButton bookDelButton;
    private javax.swing.JButton bookFindButton;
    private javax.swing.JTextField bookID;
    private javax.swing.JTextField bookName;
    private javax.swing.JTextField bookName1;
    private javax.swing.JPanel bookOpPanel;
    private javax.swing.JScrollPane bookPanel;
    private javax.swing.JButton bookSortButton;
    private javax.swing.JComboBox<String> bookSortCBox;
    private javax.swing.JTable bookTable;
    private javax.swing.JTextField category;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JLabel exit;
    private javax.swing.JButton findUserButton;
    private javax.swing.JButton giveAdminBut;
    private javax.swing.JTextField imgURL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField opUsername;
    private javax.swing.JTextField pageURL;
    private javax.swing.JTextField publisher;
    private javax.swing.JPanel userOpPanel;
    private javax.swing.JButton userSortButton;
    private javax.swing.JTable userTable;
    private javax.swing.JComboBox<String> userType;
    // End of variables declaration//GEN-END:variables
}
